apiVersion: apps/v1
kind: Deployment
metadata:
  name: newproductcatalogservice
  labels:
    app: newproductcatalogservice
spec:
  selector:
    matchLabels:
      app: newproductcatalogservice
  template:
    metadata:
      labels:
        app: newproductcatalogservice
    spec:
      serviceAccountName: productcatalogservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: newproductcatalogservice
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        - name: VERTEX_AI_SEARCH_ENABLED
          value: "true"
        - name: PROJECT_ID
          value: "partarch-ecommerce-demo"
        - name: LOCATION
          value: "global"
        - name: CATALOG
          value: "default_catalog"
        - name: BRANCH
          value: "default_branch"
        readinessProbe:
          grpc:
            port: 3550
        livenessProbe:
          grpc:
            port: 3550
        resources:
          requests:
            cpu: 400m
            memory: 256Mi
          limits:
            cpu: 600m
            memory: 512Mi