apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- newproductcatalogservice-deployment.yaml
- newproductcatalogservice-service.yaml

namespace: default

commonLabels:
  app: newproductcatalogservice

namePrefix: newproductcatalogservice-